version: "3.9"
services:

  ui:
    build: ./ui
    container_name: ui
    restart: always
    ports:
      - "3000:3000"

  flask-app:
    build: ./flask
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
        - "80:80"
    depends_on:
        - ui